// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry mirrors raft.Log in internal/raft/state.go.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Entry         []byte                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetEntry() []byte {
	if x != nil {
		return x.Entry
	}
	return nil
}

type RequestVoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,2,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,3,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReq) Reset() {
	*x = RequestVoteReq{}
	mi := &file_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReq) ProtoMessage() {}

func (x *RequestVoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReq.ProtoReflect.Descriptor instead.
func (*RequestVoteReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVoteReq) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReq) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteReq) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RequestVoteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestVoteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRes) Reset() {
	*x = RequestVoteRes{}
	mi := &file_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRes) ProtoMessage() {}

func (x *RequestVoteRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRes.ProtoReflect.Descriptor instead.
func (*RequestVoteRes) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteRes) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRes) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntryReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term              int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	PrevLogIndex      int64                  `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm       int64                  `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	LeaderCommitIndex int64                  `protobuf:"varint,5,opt,name=leader_commit_index,json=leaderCommitIndex,proto3" json:"leader_commit_index,omitempty"`
	Entries           []*LogEntry            `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendEntryReq) Reset() {
	*x = AppendEntryReq{}
	mi := &file_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntryReq) ProtoMessage() {}

func (x *AppendEntryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntryReq.ProtoReflect.Descriptor instead.
func (*AppendEntryReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppendEntryReq) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntryReq) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntryReq) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntryReq) GetLeaderCommitIndex() int64 {
	if x != nil {
		return x.LeaderCommitIndex
	}
	return 0
}

func (x *AppendEntryReq) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AppendEntryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Appended      bool                   `protobuf:"varint,2,opt,name=appended,proto3" json:"appended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntryRes) Reset() {
	*x = AppendEntryRes{}
	mi := &file_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntryRes) ProtoMessage() {}

func (x *AppendEntryRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntryRes.ProtoReflect.Descriptor instead.
func (*AppendEntryRes) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntryRes) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntryRes) GetAppended() bool {
	if x != nil {
		return x.Appended
	}
	return false
}

type InstallSnapshotReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Term              int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LastIncludedIndex int64                  `protobuf:"varint,3,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  int64                  `protobuf:"varint,4,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Data              []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Offset            int64                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Done              bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotReq) Reset() {
	*x = InstallSnapshotReq{}
	mi := &file_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotReq) ProtoMessage() {}

func (x *InstallSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotReq.ProtoReflect.Descriptor instead.
func (*InstallSnapshotReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *InstallSnapshotReq) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotReq) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotReq) GetLastIncludedIndex() int64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotReq) GetLastIncludedTerm() int64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstallSnapshotReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InstallSnapshotReq) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type InstallSnapshotRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotRes) Reset() {
	*x = InstallSnapshotRes{}
	mi := &file_proto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRes) ProtoMessage() {}

func (x *InstallSnapshotRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRes.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRes) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSnapshotRes) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type GetStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateReq) Reset() {
	*x = GetStateReq{}
	mi := &file_proto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReq) ProtoMessage() {}

func (x *GetStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReq.ProtoReflect.Descriptor instead.
func (*GetStateReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{7}
}

type GetStateRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Term  int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// role: 0 = Follower, 1 = Candidate, 2 = Leader (matches the iota in state.go).
	Role          int32       `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	Logs          []*LogEntry `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	CommitIndex   int64       `protobuf:"varint,4,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied   int64       `protobuf:"varint,5,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRes) Reset() {
	*x = GetStateRes{}
	mi := &file_proto_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRes) ProtoMessage() {}

func (x *GetStateRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRes.ProtoReflect.Descriptor instead.
func (*GetStateRes) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{8}
}

func (x *GetStateRes) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *GetStateRes) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GetStateRes) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetStateRes) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *GetStateRes) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

type SubmitCommandReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []byte                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommandReq) Reset() {
	*x = SubmitCommandReq{}
	mi := &file_proto_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommandReq) ProtoMessage() {}

func (x *SubmitCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommandReq.ProtoReflect.Descriptor instead.
func (*SubmitCommandReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitCommandReq) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type SubmitCommandRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommandRes) Reset() {
	*x = SubmitCommandRes{}
	mi := &file_proto_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommandRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommandRes) ProtoMessage() {}

func (x *SubmitCommandRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommandRes.ProtoReflect.Descriptor instead.
func (*SubmitCommandRes) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitCommandRes) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SubmitCommandRes) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *SubmitCommandRes) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

type SetPartitionedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitioned   bool                   `protobuf:"varint,1,opt,name=partitioned,proto3" json:"partitioned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPartitionedReq) Reset() {
	*x = SetPartitionedReq{}
	mi := &file_proto_raft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPartitionedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPartitionedReq) ProtoMessage() {}

func (x *SetPartitionedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPartitionedReq.ProtoReflect.Descriptor instead.
func (*SetPartitionedReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{11}
}

func (x *SetPartitionedReq) GetPartitioned() bool {
	if x != nil {
		return x.Partitioned
	}
	return false
}

type SetPartitionedRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPartitionedRes) Reset() {
	*x = SetPartitionedRes{}
	mi := &file_proto_raft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPartitionedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPartitionedRes) ProtoMessage() {}

func (x *SetPartitionedRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPartitionedRes.ProtoReflect.Descriptor instead.
func (*SetPartitionedRes) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{12}
}

var File_proto_raft_proto protoreflect.FileDescriptor

const file_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x10proto/raft.proto\x12\araft.v1\"4\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x14\n" +
	"\x05entry\x18\x02 \x01(\fR\x05entry\"~\n" +
	"\x0eRequestVoteReq\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12$\n" +
	"\x0elast_log_index\x18\x02 \x01(\x03R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x03 \x01(\x03R\vlastLogTerm\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"G\n" +
	"\x0eRequestVoteRes\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\xdb\x01\n" +
	"\x0eAppendEntryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x03R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x03R\vprevLogTerm\x12.\n" +
	"\x13leader_commit_index\x18\x05 \x01(\x03R\x11leaderCommitIndex\x12+\n" +
	"\aentries\x18\x06 \x03(\v2\x11.raft.v1.LogEntryR\aentries\"@\n" +
	"\x0eAppendEntryRes\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\bappended\x18\x02 \x01(\bR\bappended\"\xe3\x01\n" +
	"\x12InstallSnapshotReq\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\x12.\n" +
	"\x13last_included_index\x18\x03 \x01(\x03R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x04 \x01(\x03R\x10lastIncludedTerm\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\"(\n" +
	"\x12InstallSnapshotRes\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\"\r\n" +
	"\vGetStateReq\"\xa2\x01\n" +
	"\vGetStateRes\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12%\n" +
	"\x04logs\x18\x03 \x03(\v2\x11.raft.v1.LogEntryR\x04logs\x12!\n" +
	"\fcommit_index\x18\x04 \x01(\x03R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x05 \x01(\x03R\vlastApplied\",\n" +
	"\x10SubmitCommandReq\x12\x18\n" +
	"\acommand\x18\x01 \x01(\fR\acommand\"Y\n" +
	"\x10SubmitCommandRes\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\"5\n" +
	"\x11SetPartitionedReq\x12 \n" +
	"\vpartitioned\x18\x01 \x01(\bR\vpartitioned\"\x13\n" +
	"\x11SetPartitionedRes2\xd7\x01\n" +
	"\x04Raft\x12?\n" +
	"\vRequestVote\x12\x17.raft.v1.RequestVoteReq\x1a\x17.raft.v1.RequestVoteRes\x12A\n" +
	"\rAppendEntries\x12\x17.raft.v1.AppendEntryReq\x1a\x17.raft.v1.AppendEntryRes\x12K\n" +
	"\x0fInstallSnapshot\x12\x1b.raft.v1.InstallSnapshotReq\x1a\x1b.raft.v1.InstallSnapshotRes2\xd6\x01\n" +
	"\vRaftControl\x126\n" +
	"\bGetState\x12\x14.raft.v1.GetStateReq\x1a\x14.raft.v1.GetStateRes\x12E\n" +
	"\rSubmitCommand\x12\x19.raft.v1.SubmitCommandReq\x1a\x19.raft.v1.SubmitCommandRes\x12H\n" +
	"\x0eSetPartitioned\x12\x1a.raft.v1.SetPartitionedReq\x1a\x1a.raft.v1.SetPartitionedResB&Z$github.com/peartes/raft/proto;raftpbb\x06proto3"

var (
	file_proto_raft_proto_rawDescOnce sync.Once
	file_proto_raft_proto_rawDescData []byte
)

func file_proto_raft_proto_rawDescGZIP() []byte {
	file_proto_raft_proto_rawDescOnce.Do(func() {
		file_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)))
	})
	return file_proto_raft_proto_rawDescData
}

var file_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_raft_proto_goTypes = []any{
	(*LogEntry)(nil),           // 0: raft.v1.LogEntry
	(*RequestVoteReq)(nil),     // 1: raft.v1.RequestVoteReq
	(*RequestVoteRes)(nil),     // 2: raft.v1.RequestVoteRes
	(*AppendEntryReq)(nil),     // 3: raft.v1.AppendEntryReq
	(*AppendEntryRes)(nil),     // 4: raft.v1.AppendEntryRes
	(*InstallSnapshotReq)(nil), // 5: raft.v1.InstallSnapshotReq
	(*InstallSnapshotRes)(nil), // 6: raft.v1.InstallSnapshotRes
	(*GetStateReq)(nil),        // 7: raft.v1.GetStateReq
	(*GetStateRes)(nil),        // 8: raft.v1.GetStateRes
	(*SubmitCommandReq)(nil),   // 9: raft.v1.SubmitCommandReq
	(*SubmitCommandRes)(nil),   // 10: raft.v1.SubmitCommandRes
	(*SetPartitionedReq)(nil),  // 11: raft.v1.SetPartitionedReq
	(*SetPartitionedRes)(nil),  // 12: raft.v1.SetPartitionedRes
}
var file_proto_raft_proto_depIdxs = []int32{
	0,  // 0: raft.v1.AppendEntryReq.entries:type_name -> raft.v1.LogEntry
	0,  // 1: raft.v1.GetStateRes.logs:type_name -> raft.v1.LogEntry
	1,  // 2: raft.v1.Raft.RequestVote:input_type -> raft.v1.RequestVoteReq
	3,  // 3: raft.v1.Raft.AppendEntries:input_type -> raft.v1.AppendEntryReq
	5,  // 4: raft.v1.Raft.InstallSnapshot:input_type -> raft.v1.InstallSnapshotReq
	7,  // 5: raft.v1.RaftControl.GetState:input_type -> raft.v1.GetStateReq
	9,  // 6: raft.v1.RaftControl.SubmitCommand:input_type -> raft.v1.SubmitCommandReq
	11, // 7: raft.v1.RaftControl.SetPartitioned:input_type -> raft.v1.SetPartitionedReq
	2,  // 8: raft.v1.Raft.RequestVote:output_type -> raft.v1.RequestVoteRes
	4,  // 9: raft.v1.Raft.AppendEntries:output_type -> raft.v1.AppendEntryRes
	6,  // 10: raft.v1.Raft.InstallSnapshot:output_type -> raft.v1.InstallSnapshotRes
	8,  // 11: raft.v1.RaftControl.GetState:output_type -> raft.v1.GetStateRes
	10, // 12: raft.v1.RaftControl.SubmitCommand:output_type -> raft.v1.SubmitCommandRes
	12, // 13: raft.v1.RaftControl.SetPartitioned:output_type -> raft.v1.SetPartitionedRes
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_raft_proto_init() }
func file_proto_raft_proto_init() {
	if File_proto_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_raft_proto_goTypes,
		DependencyIndexes: file_proto_raft_proto_depIdxs,
		MessageInfos:      file_proto_raft_proto_msgTypes,
	}.Build()
	File_proto_raft_proto = out.File
	file_proto_raft_proto_goTypes = nil
	file_proto_raft_proto_depIdxs = nil
}
