// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/raft.proto

package raftpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Raft_RequestVote_FullMethodName     = "/raft.v1.Raft/RequestVote"
	Raft_AppendEntries_FullMethodName   = "/raft.v1.Raft/AppendEntries"
	Raft_InstallSnapshot_FullMethodName = "/raft.v1.Raft/InstallSnapshot"
)

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClient interface {
	RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteRes, error)
	AppendEntries(ctx context.Context, in *AppendEntryReq, opts ...grpc.CallOption) (*AppendEntryRes, error)
	InstallSnapshot(ctx context.Context, in *InstallSnapshotReq, opts ...grpc.CallOption) (*InstallSnapshotRes, error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestVoteRes)
	err := c.cc.Invoke(ctx, Raft_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntryReq, opts ...grpc.CallOption) (*AppendEntryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntryRes)
	err := c.cc.Invoke(ctx, Raft_AppendEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) InstallSnapshot(ctx context.Context, in *InstallSnapshotReq, opts ...grpc.CallOption) (*InstallSnapshotRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallSnapshotRes)
	err := c.cc.Invoke(ctx, Raft_InstallSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
// All implementations must embed UnimplementedRaftServer
// for forward compatibility.
type RaftServer interface {
	RequestVote(context.Context, *RequestVoteReq) (*RequestVoteRes, error)
	AppendEntries(context.Context, *AppendEntryReq) (*AppendEntryRes, error)
	InstallSnapshot(context.Context, *InstallSnapshotReq) (*InstallSnapshotRes, error)
	mustEmbedUnimplementedRaftServer()
}

// UnimplementedRaftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftServer struct{}

func (UnimplementedRaftServer) RequestVote(context.Context, *RequestVoteReq) (*RequestVoteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftServer) AppendEntries(context.Context, *AppendEntryReq) (*AppendEntryRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedRaftServer) InstallSnapshot(context.Context, *InstallSnapshotReq) (*InstallSnapshotRes, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallSnapshot not implemented")
}
func (UnimplementedRaftServer) mustEmbedUnimplementedRaftServer() {}
func (UnimplementedRaftServer) testEmbeddedByValue()              {}

// UnsafeRaftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftServer will
// result in compilation errors.
type UnsafeRaftServer interface {
	mustEmbedUnimplementedRaftServer()
}

func RegisterRaftServer(s grpc.ServiceRegistrar, srv RaftServer) {
	// If the following call panics, it indicates UnimplementedRaftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Raft_ServiceDesc, srv)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_InstallSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallSnapshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).InstallSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_InstallSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).InstallSnapshot(ctx, req.(*InstallSnapshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Raft_ServiceDesc is the grpc.ServiceDesc for Raft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Raft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.v1.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "InstallSnapshot",
			Handler:    _Raft_InstallSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}

const (
	RaftControl_GetState_FullMethodName       = "/raft.v1.RaftControl/GetState"
	RaftControl_SubmitCommand_FullMethodName  = "/raft.v1.RaftControl/SubmitCommand"
	RaftControl_SetPartitioned_FullMethodName = "/raft.v1.RaftControl/SetPartitioned"
)

// RaftControlClient is the client API for RaftControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftControlClient interface {
	GetState(ctx context.Context, in *GetStateReq, opts ...grpc.CallOption) (*GetStateRes, error)
	SubmitCommand(ctx context.Context, in *SubmitCommandReq, opts ...grpc.CallOption) (*SubmitCommandRes, error)
	SetPartitioned(ctx context.Context, in *SetPartitionedReq, opts ...grpc.CallOption) (*SetPartitionedRes, error)
}

type raftControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftControlClient(cc grpc.ClientConnInterface) RaftControlClient {
	return &raftControlClient{cc}
}

func (c *raftControlClient) GetState(ctx context.Context, in *GetStateReq, opts ...grpc.CallOption) (*GetStateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateRes)
	err := c.cc.Invoke(ctx, RaftControl_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftControlClient) SubmitCommand(ctx context.Context, in *SubmitCommandReq, opts ...grpc.CallOption) (*SubmitCommandRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCommandRes)
	err := c.cc.Invoke(ctx, RaftControl_SubmitCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftControlClient) SetPartitioned(ctx context.Context, in *SetPartitionedReq, opts ...grpc.CallOption) (*SetPartitionedRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPartitionedRes)
	err := c.cc.Invoke(ctx, RaftControl_SetPartitioned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftControlServer is the server API for RaftControl service.
// All implementations must embed UnimplementedRaftControlServer
// for forward compatibility.
type RaftControlServer interface {
	GetState(context.Context, *GetStateReq) (*GetStateRes, error)
	SubmitCommand(context.Context, *SubmitCommandReq) (*SubmitCommandRes, error)
	SetPartitioned(context.Context, *SetPartitionedReq) (*SetPartitionedRes, error)
	mustEmbedUnimplementedRaftControlServer()
}

// UnimplementedRaftControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftControlServer struct{}

func (UnimplementedRaftControlServer) GetState(context.Context, *GetStateReq) (*GetStateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedRaftControlServer) SubmitCommand(context.Context, *SubmitCommandReq) (*SubmitCommandRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCommand not implemented")
}
func (UnimplementedRaftControlServer) SetPartitioned(context.Context, *SetPartitionedReq) (*SetPartitionedRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPartitioned not implemented")
}
func (UnimplementedRaftControlServer) mustEmbedUnimplementedRaftControlServer() {}
func (UnimplementedRaftControlServer) testEmbeddedByValue()                     {}

// UnsafeRaftControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftControlServer will
// result in compilation errors.
type UnsafeRaftControlServer interface {
	mustEmbedUnimplementedRaftControlServer()
}

func RegisterRaftControlServer(s grpc.ServiceRegistrar, srv RaftControlServer) {
	// If the following call panics, it indicates UnimplementedRaftControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftControl_ServiceDesc, srv)
}

func _RaftControl_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftControlServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftControl_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftControlServer).GetState(ctx, req.(*GetStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftControl_SubmitCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftControlServer).SubmitCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftControl_SubmitCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftControlServer).SubmitCommand(ctx, req.(*SubmitCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftControl_SetPartitioned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPartitionedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftControlServer).SetPartitioned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftControl_SetPartitioned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftControlServer).SetPartitioned(ctx, req.(*SetPartitionedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftControl_ServiceDesc is the grpc.ServiceDesc for RaftControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.v1.RaftControl",
	HandlerType: (*RaftControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _RaftControl_GetState_Handler,
		},
		{
			MethodName: "SubmitCommand",
			Handler:    _RaftControl_SubmitCommand_Handler,
		},
		{
			MethodName: "SetPartitioned",
			Handler:    _RaftControl_SetPartitioned_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}
